version: 0.2

env:
  variables:
    NODE_VERSION: "22"

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo "Installing pnpm..."
      - npm install -g pnpm@8

      - node --version
      - pnpm --version

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pnpm install --no-frozen-lockfile

      - echo "Running lint..."
      - pnpm run ci:lint

      - echo "Running typecheck..."
      - pnpm run ci:typecheck
  
  build:
    commands:
      - echo "build..."
      - pnpm run build
  
  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://${BUCKET_NAME}
      - aws cloudfront create-invalidation --distribution-id ${CLOUD_FRONT_ID} --paths /index.html

cache:
  paths:
    - ~/.pnpm-store/**/*
